name: vprofile actions
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
    AWS_REGION: us-east-1
    ECR_REPOSITORY: mreg
    EKS_CLUSTER: vprofile-eks


jobs:
    Testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build
              run: mvn test

            - name: checkstyle
              run: mvn checkstyle:checkstyle

            - name: setup java
              uses: actions/setup-java@v3
              with:
                java-version: '11'
                distribution: 'temurin'
            
            - name: setup sonarqube
              uses: warchant/setup-sonar-scanner@v7

    Build and Publish: 
        runs-on: ubuntu-latest
        needs: Testing
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build and Publish to ECR
              uses: appleboy/docker-ecr-action@master
              with:
                access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                region: ${{ env.AWS_REGION }}
                repository: ${{ secrets.REGISTRY }}
                repo: ${{env.ECR_REPOSITORY}}
                tags: latest,${{github.run_number}}
                daemon_off: false
                dockerfile: ./Dockerfile
                context: ./
      
